### ISSUE TITLE
google_sql_user.ert: Error, failed to get user ...

### ISSUE THREAD

**Issue by dgruber** [pivotal-cf/gcp-concourse#10]
I got an error in the create_infrastructure job after the DB was created at the final step were a pre-defined DB user and password is set. When watching that on google console the DB is created and also the user is there but somehow terraform complains about that.

That is the terraform step:

'''
-resource "google_sql_user" "ert" {
-  name       = "${var.ert_sql_db_username}"
-  depends_on = ["google_sql_database.diego"]
-  password   = "${var.ert_sql_db_password}"
-  instance   = "${google_sql_database_instance.master.name}"
-  host       = "%"
-
-  count = "1"
-}
'''

After removing it works great, but of course there are no DB credentials.

The error message I'm getting:

'''
google_sql_database.routing: Creation complete
google_sql_database.diego: Creating...
  instance:  "" => "concourse-terraform2-sql-2fd6d269-a7a5-4615-a256-6e03c5ea2034"
  name:      "" => "diego"
  self_link: "" => "<computed>"
google_sql_database.diego: Creation complete
google_sql_user.ert: Creating...
  host:     "" => "%"
  instance: "" => "concourse-terraform2-sql-2fd6d269-a7a5-4615-a256-6e03c5ea2034"
  name:     "" => "admin"
  password: "" => "XXX_Deleted_That_Password_XXX"
google_sql_user.ert: Still creating... (10s elapsed)
google_sql_user.ert: Still creating... (20s elapsed)
google_sql_user.ert: Still creating... (30s elapsed)
Error applying plan:

1 error(s) occurred:

* google_sql_user.ert: Error, failed to get user admin in instance concourse-terraform2-sql-2fd6d269-a7a5-4615-a256-6e03c5ea2034: googleapi: Error 500: Backend Error, backendError

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
'''

The second thing I noticed is that the pipeline.yml refers to others github repos. Shouldn't point them to the repo here? Otherwise it becomes harder to manage (self configure when checked out)?

Really great stuff that pipe!

**Comment by dgruber** [comment]
Looks like a terraform issue (similar to https://github.com/hashicorp/terraform/issues/8025). When switching to first generation Google DB or internal it works (sql.tf   settings {
-    tier = "db-f1-micro"
+    tier = "D0" )

**Comment by krishicks** [comment]
Interesting. Another user has run into the same problem. We'll take a look!

**Comment by stwomack** [comment]
I had the same issue when using my own fork, and changing tier = "D0"

**Comment by stwomack** [comment]
When I also hard-coded the "region" to "us-central" as well, in sql.tf , I was able to get past this. Can't simply change the gcp_region param because other other resources need to be us-central1, while the legacy sql one only considers us-central as valid.

**Comment by krishicks** [comment]
I've created a story for this: https://www.pivotaltracker.com/story/show/143967561

**Comment by krishicks** [comment]
This repo is being deprecated in favor of https://github.com/pivotal-cf/pcf-pipelines which has an install-pcf pipeline for GCP.

Please open a new issue there if this is still a problem.
