### ISSUE TITLE
GCP Deploy ERT Fails

### ISSUE THREAD

**Issue by rjain-pivotal** [pivotal-cf/gcp-concourse#8]
I have been using the pipeline for a while, and today with the new 1.9.3 release, I am getting this error

```
Deploying ERT @ https://opsman.gcp.rjainpcf.com ...
Found ERT Deployment with guid of cf-0113bdcc7303035e8a28
Setting Availability Zones & Networks for: cf-0113bdcc7303035e8a28
{}
Setting Properties for: cf-0113bdcc7303035e8a28
Error Call Failed ....
 X-Xss-Protection: 1; mode=block0-ae39-7c9492e8f586cache
```

**Comment by krishicks** [comment]
@rjain-pivotal Is this still an issue for you?

**Comment by krishicks** [comment]
Closing this issue as this issue is old and the repo is deprecated in favor of https://github.com/pivotal-cf/pcf-pipelines.
