### ISSUE TITLE
Terraformed firewall rule allow-ert-all overly restrictive

### ISSUE THREAD

**Issue by cholick** [pivotal-cf/gcp-concourse#9]
GCP installation instructions don't restrict traffic flow to tags, see:
http://docs.pivotal.io/pivotalcf/1-9/customizing/gcp-prepare-env.html#firewall_rules

But the terraformed firewall rule for internal traffic does:
https://github.com/pivotal-cf/gcp-concourse/blob/master/terraform/firewalls.tf#L76-#L77

This creates traffic issues on bosh-deployed / odb vms, which don't get tagged in the same way.

cc @JaredGordon @miyer-pivotal

**Comment by krishicks** [comment]
@cholick I've created a story for this: https://www.pivotaltracker.com/story/show/143967429

**Comment by JaredGordon** [comment]
+1

**Comment by krishicks** [comment]
@cholick I'm closing this in favor of https://github.com/pivotal-cf/pcf-pipelines/issues/71, which is a copy of your issue but in the pcf-pipelines repository that replaces this one.
